-- Create a table for public todos
create table todos (
  id bigint generated by default as identity primary key,
  title text not null,
  is_complete boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Set up Row Level Security (RLS)
-- For this simple demo, we allow anyone to read and write
alter table todos enable row level security;

create policy "Anyone can view todos"
on todos for select
using (true);

create policy "Anyone can insert todos"
on todos for insert
with check (true);

create policy "Anyone can update todos"
on todos for update
using (true);

create policy "Anyone can delete todos"
on todos for delete
using (true);
